"""schemas.py

Pydantic input and output schemas for the FastAPI prediction service and evaluation endpoints.
"""

from typing import Literal
from pydantic import BaseModel, Field


class CodelistRequest(BaseModel):
    """Input payload for generating a clinical codelist."""

    condition: str = Field(..., description="Clinical condition or phenotype name", json_schema_extra={"example": "Asthma"})
    strategy: Literal["zero_shot", "few_shot", "chain_of_thought"] = Field(
        "zero_shot", description="Prompting strategy"
    )
    use_rag: bool = Field(True, description="Enable retrieval-augmented generation")
    n_results: int = Field(400, description="Number of retrieved concepts for RAG context", ge=10, le=1000)
    provider: Literal["openai", "google", "anthropic", "ollama"] = Field("openai", description="LLM provider")
    model: str = Field("gpt-5.5", description="LLM model identifier")
    base_url: str | None = Field(None, description="Optional custom endpoint URL for Ollama/vLLM")


class CodelistItem(BaseModel):
    """Single SNOMED-CT concept entry in a generated codelist."""

    code: str = Field(..., description="SNOMED-CT concept identifier", json_schema_extra={"example": "195967001"})
    term: str = Field(..., description="Concept description term", json_schema_extra={"example": "Asthma"})
    code_is_real: bool | None = Field(
        None, description="True if verified against loaded terminology; False if fabricated"
    )


class CodelistResponse(BaseModel):
    """Output response payload returned by the prediction service."""

    condition: str
    success: bool
    error: str | None = None
    codes: list[CodelistItem] = Field(default_factory=list)
    total_codes: int = 0
    fabrication_rate: float | None = None
    n_retrieved: int = 0
    attempts: int = 1
    strategy: str
    use_rag: bool
    model: str
    version: str = Field(..., description="codelist-rag package version that produced the response")
    disclaimer: str = (
        "Research tool only. Codelists generated by AI must be reviewed and "
        "validated by a qualified clinician before use in electronic health record research."
    )


class EvaluationRequest(BaseModel):
    """Input payload for scoring a generated codelist against a gold standard."""

    generated_codes: list[dict[str, str]] = Field(..., description="List of dicts with 'code' and 'term'")
    gold_codes: list[str] = Field(..., description="List of gold standard code strings")
    retrieval_type: Literal["rag", "non_rag"] = Field("rag", description="Retrieval mode")
    retrieved_codes: list[str] = Field(default_factory=list, description="List of retrieved code strings")


class EvaluationResponse(BaseModel):
    """Evaluation metrics summary."""

    precision: float
    recall: float
    f1: float
    f05: float
    true_positives: int
    false_positives: int
    false_negatives: int
    generated_count: int
    gold_count: int
    size_ratio: float
    failure_attribution: list[dict[str, str]] = Field(default_factory=list)
